name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: nuget
      run: nuget restore
    - name: Build
      run: dotnet build --configuration Release
    - name: artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: D:\a\TellTaleWidescreenPatcher\TellTaleWidescreenPatcher\TellTaleWidescreenPatcher\bin\Release\
